#!/bin/bash
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -e /usr/lib/sshplus ]] && rm -rf /bin/mtuning > /dev/null 2>&1
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;34m/"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
IP=$(cat /etc/IP)
x="ok"
mtuning ()
{
velocity () {
aguarde () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -d /etc/SSHPlus ]] && rm -rf /bin/menu
${comando[0]} > /dev/null 2>&1
${comando[1]} > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mCARREGANDO \033[1;37m\033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;34m/"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mCARREGANDO \033[1;37m\033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m\033[1;32m CONCLUIDO !\033[1;37m"
tput cnorm
}
fun_tst () {
speedtest --share > speed
}
echo ""
echo -e "   \033[1;36mTESTANDO A VELOCIDADE DE BANDA !\033[0m"
echo ""
aguarde 'fun_tst'
echo ""
png=$(cat speed | sed -n '5 p' |awk -F : {'print $NF'})
down=$(cat speed | sed -n '7 p' |awk -F :  {'print $NF'})
upl=$(cat speed | sed -n '9 p' |awk -F :  {'print $NF'})
lnk=$(cat speed | sed -n '10 p' |awk {'print $NF'})
echo -e "\033[0;37m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;33mDOWN:\033[1;37m[ $down ]    \033[1;33m UP: \033[1;37m[ $upl ]     \033[1;33mPING: \033[1;37m[ $png ]"
echo -e ""
echo -e "\033[1;33mLINK: \033[1;37m$lnk\033[0m"
echo -e "\033[0;37m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
rm -rf $HOME/speed
}

#]
function onapp1 () {
clear
echo -e "\n\033[1;32mINICIANDO O ONLINE APP... \033[0m"
echo ""
apt install apache2 -y > /dev/null 2>&1
sed -i "s/Listen 80/Listen 8888/g" /etc/apache2/ports.conf >/dev/null 2>&1
service apache2 restart
rm -rf /var/www/html/server >/dev/null 2>&1
mkdir /var/www/html/server >/dev/null 2>&1
fun_bar 'screen -dmS onlineapp onlineapp' 'sleep 3'
[[ $(grep -wc "onlineapp" /etc/autostart) = '0' ]] && {
echo -e "ps x | grep 'onlineapp' | grep -v 'grep' && echo 'ON' || screen -dmS onlineapp onlineapp" >> /etc/autostart
} || {
sed -i '/onlineapp/d' /etc/autostart
echo -e "ps x | grep 'onlineapp' | grep -v 'grep' && echo 'ON' || screen -dmS onlineapp onlineapp" >> /etc/autostart
}
IP=$(wget -qO- ipv4.icanhazip.com) >/dev/null 2>&1
echo -e "\n\033[1;32m  ONLINE APP ATIVO !\033[0m"
echo -e "\033[1;31m \033[1;33mURL de Usuários Online para usar no App\033[0m"
echo -e " http://$IP:8888/server/online"
sleep 10s
menu
}
function onapp2 () {
clear
echo -e "\033[1;32mPARANDO O ONLINE APP... \033[0m"
echo ""
fun_stponlineapp () {
sleep 1s
screen -r -S "onlineapp" -X quit
screen -wipe 1>/dev/null 2>/dev/null
[[ $(grep -wc "onlineapp" /etc/autostart) != '0' ]] && {
sed -i '/onlineapp/d' /etc/autostart
}
sleep 1s
}
fun_bar 'fun_stponlineapp' 'sleep 3'
rm -rf /var/www/html/server >/dev/null 2>&1
echo -e "\n\033[1;31m ONLINE APP PARADO !\033[0m"
sleep 3s
menu
}
function onapp_ssh () {
[[ $(ps x | grep "onlineapp"|grep -v grep |wc -l) = '0' ]] && onapp1 || onapp2
}
#menu2
menu2 (){
stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉)" || echo -e "\033[1;31m(OFF ○)")
stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉)" || echo -e "\033[1;31m(OFF ○)")
stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○) ")
stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉)" || echo -e "\033[1;31m(OFF ○)")
autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○)")
_swap1=$(free -h | grep -i swap | awk {'print $2'})
[[ -e /etc/Plus-torrent ]] && stsf=$(echo -e "\033[1;32m(ON ◉)") || stsf=$(echo -e "\033[1;31m(OFF ○)")
ram1=$(free -h | grep -i mem | awk {'print $2'})
cpucores=$(grep -c cpu[0-9] /proc/stat)
atual=$(cat /proc/sys/net/core/rmem_default)
atual2=$(cat /proc/sys/net/ipv4/tcp_congestion_control)
clear
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;34m<\033[1;37m01 ×\033[1;34m> \033[1;33mBuffer 16Mb \033[1;31m\033[1;37m[ Buffer Suave ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m02 ×\033[1;34m> \033[1;33mBuffer 32Mb \033[1;31m\033[1;37m[ Buffer Balanceado ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m03 ×\033[1;34m> \033[1;33mBuffer 54Mb \033[1;31m\033[1;37m[ Buffer Extremo ]\033[0;32m"
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;34m<\033[1;37m04 ×\033[1;34m> \033[1;33mTxqueuelen Suave \033[1;31m\033[1;37m[ Transmitir 5.000 Pacotes Eth0 ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m05 ×\033[1;34m> \033[1;33mTxqueuelen Balanceado \033[1;31m\033[1;37m[ Transmitir 10.000 Pacotes Eth0 ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m06 ×\033[1;34m> \033[1;33mTxqueuelen Extremo \033[1;31m\033[1;37m[ Transmitir 16.384 Pacotes Eth0 ]\033[0;32m"
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;34m<\033[1;37m07 ×\033[1;34m> \033[1;33mAlgoritmo BBR \033[1;31m\033[1;37m[ Congestionamento BBR ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m08 ×\033[1;34m> \033[1;33mAlgoritmo Illinois \033[1;31m\033[1;37m[ Congestionamento Illinois ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m09 ×\033[1;34m> \033[1;33mMtu Pacote Jumbo\033[1;31m\033[1;37m [ Transmitir Mtu 9.000 Jumbo Frames ]\033[0;32m"
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;34m<\033[1;37m10 ×\033[1;34m> \033[1;33mInitCwnd \033[1;31m\033[1;37m[ Melhoria No Desempenho Tcp ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m11 ×\033[1;34m> \033[1;33mMemoria Ram \033[1;31m\033[1;37m[ Aumento De Pequenos Valores VM ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m12 ×\033[1;34m> \033[1;33mMemoria Cache \033[1;31m\033[1;37m[ Limpeza De Cache Buffer ] \033[0;32m"
echo -e "\033[0;31m-----------------------------------"
echo -e "\033[1;34m<\033[1;37m13 ×\033[1;34m> \033[1;33mBalancear Carga \033[1;31m\033[1;37m[ Interrupções De Hardware Entre CPUs ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m14 ×\033[1;34m> \033[1;33mFrequência CPU \033[1;31m\033[1;37m[ Aumentar Frequencia De Escala Entre CPUs ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m15 ×\033[1;34m> \033[1;33mEntropia Kernel \033[1;31m\033[1;37m[ Melhorar Desempenho Do Kernel ] \033[0;32m"
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;34m<\033[1;37m16 ×\033[1;34m> \033[1;33mOpenSSH \033[1;31m\033[1;37m[ Melhorar Desempenho Do SSH ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m17 ×\033[1;34m> \033[1;33mLimites \033[1;31m\033[1;37m[ Aumentar Limites Do Kernel Padrão Security ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m18 ×\033[1;34m> \033[1;33mDns Google \033[1;31m\033[1;37m[ Definir Dns IPv4 Google ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m19 ×\033[1;34m> \033[1;33mDns OpenDns \033[1;31m\033[1;37m[ Definir Dns Ipv4 OpenDns] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m20 ×\033[1;34m> \033[1;33mDns Cloudflare \033[1;31m\033[1;37m[ Definir Dns IPv4 Cloudflare ] \033[0;32m"
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;34m<\033[1;37mK | k\033[1;34m> \033[1;33mDesabilitar \033[1;31m\033[1;37m[ Redefir Todos Os Valores Definidos! ]\033[0;32m"
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;37mRick3214 SERVER MANAGER V 1.2    $date\033[1;37m"
read x

case "$x" in
   *)
menu2
esac
}
while true $x != "ok"
do
#limiter
function limit1 () {
   clear
   echo -e "\n\033[1;32mINICIANDO O LIMITADOR SSH... \033[0m"
   echo ""
   fun_bar 'screen -dmS limiter limiter' 'sleep 3'
   [[ $(grep -wc "limiter" /etc/autostart) = '0' ]] && {
       echo -e "ps x | grep 'limiter' | grep -v 'grep' && echo 'ON' || screen -dmS limiter limiter" >> /etc/autostart
   } || {
       sed -i '/limiter/d' /etc/autostart
	   echo -e "ps x | grep 'limiter' | grep -v 'grep' && echo 'ON' || screen -dmS limiter limiter" >> /etc/autostart
   }
   echo -e "\n\033[1;32m  LIMITADOR SSH ATIVO !\033[0m"
   sleep 2
   menu
}
function limit2 () {
   clear
   echo -e "\033[1;33mPARANDO O LIMITADOR SSH... \033[0m"
   echo ""
   fun_stplimiter () {
      sleep 1
      screen -r -S "limiter" -X quit
      screen -wipe 1>/dev/null 2>/dev/null
      [[ $(grep -wc "limiter" /etc/autostart) != '0' ]] && {
          sed -i '/limiter/d' /etc/autostart
      }
      sleep 1
   }
   fun_bar 'fun_stplimiter' 'sleep 3'
   echo -e "\n\033[1;31m LIMITADOR SSH PARADO !\033[0m"
   sleep 2
   menu
}
function limit_ssh () {
[[ $(ps x | grep "limiter"|grep -v grep |wc -l) = '0' ]] && limit1 || limit2
}
stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉)" || echo -e "\033[1;31m(OFF ○)")
stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉)" || echo -e "\033[1;31m(OFF ○)")
stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○) ")
stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON ◉)" || echo -e "\033[1;31m(OFF ○)")
autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m(ON ◉) " || echo -e "\033[1;31m(OFF ○)")
if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f3 /etc/issue.net)
else
system=$(cut -d' ' -f1 /etc/issue.net)
fi
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
[[ "$(cat /etc/SSHPlus/Exp)" != "" ]] && _expuser=$(cat /etc/SSHPlus/Exp) || _expuser="0"
[[ -e /etc/openvpn/openvpn-status.log ]] && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) || _onop="0"
[[ -e /etc/default/dropbear ]] && _drp=$(ps aux | grep dropbear | grep -v grep | wc -l) _ondrp=$(($_drp - 1)) || _ondrp="0"
system=$(cat /etc/issue.net)
clear
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;34m<\033[1;37m01 ×\033[1;34m> \033[1;33mBuffer 16Mb \033[1;31m\033[1;37m[ Buffer Suave ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m02 ×\033[1;34m> \033[1;33mBuffer 32Mb \033[1;31m\033[1;37m[ Buffer Balanceado ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m03 ×\033[1;34m> \033[1;33mBuffer 54Mb \033[1;31m\033[1;37m[ Buffer Extremo ]\033[0;32m"
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;34m<\033[1;37m04 ×\033[1;34m> \033[1;33mTxqueuelen Suave \033[1;31m\033[1;37m[ Transmitir 5.000 Pacotes Eth0 ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m05 ×\033[1;34m> \033[1;33mTxqueuelen Balanceado \033[1;31m\033[1;37m[ Transmitir 10.000 Pacotes Eth0 ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m06 ×\033[1;34m> \033[1;33mTxqueuelen Extremo \033[1;31m\033[1;37m[ Transmitir 16.384 Pacotes Eth0 ]\033[0;32m"
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;34m<\033[1;37m07 ×\033[1;34m> \033[1;33mAlgoritmo BBR \033[1;31m\033[1;37m[ Congestionamento BBR ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m08 ×\033[1;34m> \033[1;33mAlgoritmo Illinois \033[1;31m\033[1;37m[ Congestionamento Illinois ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m09 ×\033[1;34m> \033[1;33mMtu Pacote Jumbo\033[1;31m\033[1;37m [ Transmitir Mtu 9.000 Jumbo Frames ]\033[0;32m"
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;34m<\033[1;37m10 ×\033[1;34m> \033[1;33mInitCwnd \033[1;31m\033[1;37m[ Melhoria No Desempenho Tcp ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m11 ×\033[1;34m> \033[1;33mMemoria Ram \033[1;31m\033[1;37m[ Aumento De Pequenos Valores VM ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m12 ×\033[1;34m> \033[1;33mMemoria Cache \033[1;31m\033[1;37m[ Limpeza De Cache Buffer ] \033[0;32m"
echo -e "\033[0;31m-----------------------------------"
echo -e "\033[1;34m<\033[1;37m13 ×\033[1;34m> \033[1;33mRps Cpu \033[1;31m\033[1;37m[ Direcionar Pacotes De Recebimentos Entre VCpus ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m14 ×\033[1;34m> \033[1;33mFrequência CPU \033[1;31m\033[1;37m[ Aumentar Frequencia De Escala Entre CPUs ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m15 ×\033[1;34m> \033[1;33mEntropia Kernel \033[1;31m\033[1;37m[ Melhorar Desempenho Do Kernel ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m16 ×\033[1;34m> \033[1;33mOpenSSH \033[1;31m\033[1;37m[ Melhorar Desempenho Do SSH ] \033[0;32m"
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;34m<\033[1;37m17 ×\033[1;34m> \033[1;33mLimites \033[1;31m\033[1;37m[ Aumentar Limites Do Kernel Padrão Security ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m18 ×\033[1;34m> \033[1;33mDns Google \033[1;31m\033[1;37m[ Definir Dns IPv4 Google ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m19 ×\033[1;34m> \033[1;33mDns OpenDns \033[1;31m\033[1;37m[ Definir Dns Ipv4 OpenDns] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m20 ×\033[1;34m> \033[1;33mDns Cloudflare \033[1;31m\033[1;37m[ Definir Dns IPv4 Cloudflare ] \033[0;32m"
echo -e "\033[1;34m<\033[1;37m21 ×\033[1;34m> \033[1;33mNoatime Disco \033[1;31m\033[1;37m[ Remontar Disco Com Noatime ] \033[0;32m"
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;34m<\033[1;37m off \033[1;34m> \033[1;33mDesabilitar \033[1;31m\033[1;37m[ Redefir Todos Os Valores Definidos ]\033[0;32m"
echo -e "\033[1;34m<\033[1;37m menu \033[1;34m> \033[1;33mMenu \033[1;31m\033[1;37m[ Voltar Ao Menu Principal ]\033[0;32m"
echo -e "\033[0;31m------------------------------------"
echo -e "\033[1;37mRick3214 SERVER MANAGER V 1.3    $date\033[1;37m"

###

read x
case "$x" in

   1 | 01)
crontab -u root -l | grep -v '@reboot sleep 10s && /bin/acksyshttpack'  | crontab -u root -
   echo -ne "\n\033[1;33mBuffer Anterior : \033[1;37m"
 cat /proc/sys/net/ipv4/tcp_rmem
   echo 8388608 12582912 16777216 > /proc/sys/net/ipv4/udp_mem
   echo 8388608 12582912 16777216 > /proc/sys/net/ipv4/tcp_mem
   echo 4096 87380 16777216 > /proc/sys/net/ipv4/tcp_rmem
   echo 4096 16384 16777216 > /proc/sys/net/ipv4/tcp_wmem
   echo 16777216 > /proc/sys/net/core/rmem_default
   echo 16777216 > /proc/sys/net/core/wmem_default
   echo 16777216 > /proc/sys/net/core/rmem_max
   echo 16777216 > /proc/sys/net/core/wmem_max
   echo 16777216 > /proc/sys/net/ipv4/udp_rmem_min
   echo 16777216 > /proc/sys/net/ipv4/udp_wmem_min
echo -n > /etc/sysctl.conf
   echo "net.ipv4.udp_mem = 8388608 12582912 16777216
         net.ipv4.tcp_mem = 8388608 12582912 16777216
         net.ipv4.tcp_rmem = 4096 87380 16777216
         net.ipv4.tcp_wmem = 4096 16384 16777216
         net.core.rmem_default = 16777216
         net.core.wmem_default = 16777216
         net.core.rmem_max = 16777216
         net.core.wmem_max = 16777216
         net.ipv4.udp_rmem_min = 16777216
         net.ipv4.udp_wmem_min = 16777216" > /etc/sysctl.conf
sysctl -p > /dev/null
acksyshttpack > /dev/null 2>&1
(crontab -l; echo "@reboot sleep 10s && /bin/acksyshttpack") | crontab - > /dev/null 2>&1
   echo -ne "\n\033[1;33mBuffer Atual : \033[1;37m"
 cat /proc/sys/net/ipv4/tcp_rmem
sleep 2s
   echo -ne "\n\033[1;32mBuffer Suave Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
clear
cd /bin/ && mtuning
   ;;
   2 | 02)
crontab -u root -l | grep -v '@reboot sleep 10s && /bin/acksyshttpack'  | crontab -u root -
   echo -ne "\n\033[1;33mBuffer Anterior : \033[1;37m"
 cat /proc/sys/net/ipv4/tcp_rmem
   echo 8388608 12582912 16777216 > /proc/sys/net/ipv4/udp_mem
   echo 8388608 12582912 16777216 > /proc/sys/net/ipv4/tcp_mem
   echo 4096 4194394 33554432 > /proc/sys/net/ipv4/tcp_rmem
   echo 4096 4194394 33554432 > /proc/sys/net/ipv4/tcp_wmem
   echo 33554432 > /proc/sys/net/core/rmem_default
   echo 33554432 > /proc/sys/net/core/wmem_default
   echo 33554432 > /proc/sys/net/core/rmem_max
   echo 33554432 > /proc/sys/net/core/wmem_max
   echo 33554432 > /proc/sys/net/ipv4/udp_rmem_min
   echo 33554432 > /proc/sys/net/ipv4/udp_wmem_min
echo -n > /etc/sysctl.conf
   echo "net.ipv4.udp_mem = 8388608 12582912 16777216
   net.ipv4.tcp_mem = 8388608 12582912 16777216
   net.ipv4.tcp_rmem = 4096 4194394 33554432
   net.ipv4.tcp_wmem = 4096 4194394 33554432
   net.core.rmem_default = 33554432
   net.core.rmem_max = 33554432
   net.core.wmem_max = 33554432
   net.ipv4.udp_rmem_min = 33554432
   net.ipv4.udp_wmem_min = 33554432" > /etc/sysctl.conf
sysctl -p > /dev/null
acksyshttpack > /dev/null 2>&1
(crontab -l; echo "@reboot sleep 10s && /bin/acksyshttpack") | crontab - > /dev/null 2>&1
   echo -ne "\n\033[1;33mBuffer Atual : \033[1;37m"
 cat /proc/sys/net/ipv4/tcp_rmem
sleep 2s
   echo -ne "\n\033[1;32mBuffer balanceado Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
   ;;
   3 | 03)
crontab -u root -l | grep -v '@reboot sleep 10s && /bin/acksyshttpack'  | crontab -u root -
   echo -ne "\n\033[1;33mBuffer Anterior : \033[1;37m"
 cat /proc/sys/net/ipv4/tcp_rmem
   echo 8388608 12582912 16777216 > /proc/sys/net/ipv4/udp_mem
   echo 8388608 12582912 16777216 > /proc/sys/net/ipv4/tcp_mem
   echo 4096 4194394 56623104 > /proc/sys/net/ipv4/tcp_rmem
   echo 4096 4194394 56623104 > /proc/sys/net/ipv4/tcp_wmem
   echo 56623104 > /proc/sys/net/core/rmem_default
   echo 56623104 > /proc/sys/net/core/wmem_default
   echo 56623104 > /proc/sys/net/core/rmem_max
   echo 56623104 > /proc/sys/net/core/wmem_max
   echo 56623104 > /proc/sys/net/ipv4/udp_rmem_min
   echo 56623104 > /proc/sys/net/ipv4/udp_wmem_min
(crontab -l; echo "@reboot sleep 10s && /bin/acksyshttpack") | crontab - > /dev/null 2>&1
echo -n > /etc/sysctl.conf
   echo "net.ipv4.udp_mem = 8388608 12582912 16777216
   net.ipv4.tcp_mem = 8388608 12582912 16777216
   net.ipv4.tcp_rmem = 4096 4194394 56623104
   net.ipv4.tcp_wmem = 4096 4194394 56623104
   net.core.rmem_default = 56623104
   net.core.wmem_default = 56623104
   net.core.rmem_max = 56623104
   net.core.wmem_max = 56623104
   net.ipv4.udp_rmem_min = 56623104
   net.ipv4.udp_wmem_min = 56623104" > /etc/sysctl.conf
sysctl -p > /dev/null
acksyshttpack > /dev/null 2>&1
   echo -ne "\n\033[1;33mBuffer Atual : \033[1;37m"
 cat /proc/sys/net/ipv4/tcp_rmem
sleep 2s
   echo -ne "\n\033[1;32mBuffer Extremo Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
   ;;
   4 | 04)
echo -e "\033[1;33m Txqueuelen Atual \033[1;37m"
echo ""
ifconfig eth0
echo -e "\033[0;31m------------------------------------\033[1;37m"
echo ""
echo -n > /etc/rc.local
echo "#!/bin/bash" >> /etc/rc.local
echo "ifconfig eth0 txqueuelen 5000" >> /etc/rc.local
echo "ifconfig lo txqueuelen 5000" >> /etc/rc.local
echo "#exit 0" >> /etc/rc.local
chmod +x /etc/rc.local
  ifconfig eth0 txqueuelen 5000
  ifconfig lo txqueuelen 5000
ifconfig eth0
echo -e "\033[0;31m------------------------------------\033[1;37m"
   echo -ne "\n\033[1;32mTxqueuelen Suave Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
   ;;
   5 | 05)
echo -e "\033[1;33m Txqueuelen Atual \033[1;37m"
echo ""
ifconfig eth0
echo -e "\033[0;31m------------------------------------\033[1;37m"
echo ""
echo -n > /etc/rc.local
echo "#!/bin/bash" >> /etc/rc.local
echo "ifconfig eth0 txqueuelen 10000" >> /etc/rc.local
echo "ifconfig lo txqueuelen 10000" >> /etc/rc.local
echo "#exit 0" >> /etc/rc.local
chmod +x /etc/rc.local
  ifconfig eth0 txqueuelen 10000
  ifconfig lo txqueuelen 10000
ifconfig eth0
echo -e "\033[0;31m------------------------------------\033[1;37m"
   echo -ne "\n\033[1;32mTxqueuelen Balanceado Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
  ;;
  06 | 6)
echo -e "\033[1;33m Txqueuelen Atual \033[1;37m"
echo ""
ifconfig eth0
echo -e "\033[0;31m------------------------------------\033[1;37m"
echo ""
echo -n > /etc/rc.local
echo "#!/bin/bash" >> /etc/rc.local
echo "ifconfig eth0 txqueuelen 16384" >> /etc/rc.local
echo "ifconfig lo txqueuelen 16384" >> /etc/rc.local
echo "#exit 0" >> /etc/rc.local
chmod +x /etc/rc.local
  ifconfig eth0 txqueuelen 16384
  ifconfig lo txqueuelen 16384
ifconfig eth0
echo -e "\033[0;31m------------------------------------\033[1;37m"
   echo -ne "\n\033[1;32mTxqueuelen Extremo Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
   ;;
   07 | 7)
   echo -ne "\n\033[1;33mCongestionamento Anterior : \033[1;37m"
crontab -u root -l | grep -v '@reboot sleep 10s &&  echo illinois > /proc/sys/net/ipv4/tcp_congestion_control && echo illinois > /proc/sys/net/ipv4/tcp_allowed_congestion_control && echo fq > /proc/sys/net/core/default_qdisc'  | crontab -u root -
crontab -u root -l | grep -v '@reboot sleep 10s &&  echo bbr > /proc/sys/net/ipv4/tcp_congestion_control && echo bbr > /proc/sys/net/ipv4/tcp_allowed_congestion_control && echo fq > /proc/sys/net/core/default_qdisc'  | crontab -u root -
 cat /proc/sys/net/ipv4/tcp_congestion_control
   echo bbr > /proc/sys/net/ipv4/tcp_congestion_control
   echo bbr > /proc/sys/net/ipv4/tcp_allowed_congestion_control
   echo fq > /proc/sys/net/core/default_qdisc
(crontab -l; echo "@reboot sleep 10s &&  echo bbr > /proc/sys/net/ipv4/tcp_congestion_control && echo bbr > /proc/sys/net/ipv4/tcp_allowed_congestion_control && echo fq > /proc/sys/net/core/default_qdisc") | crontab - > /dev/null 2>&1
   echo -ne "\n\033[1;33mCongestionamento Atual : \033[1;37m"
 cat /proc/sys/net/ipv4/tcp_congestion_control
sleep 2s
   echo -ne "\n\033[1;32mCongestionamento BBR Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
   ;;
   08 | 8)
   echo -ne "\n\033[1;33mCongestionamento Anterior : \033[1;37m"
crontab -u root -l | grep -v '@reboot sleep 10s &&  echo bbr > /proc/sys/net/ipv4/tcp_congestion_control && echo bbr > /proc/sys/net/ipv4/tcp_allowed_congestion_control && echo fq > /proc/sys/net/core/default_qdisc'  | crontab -u root -
crontab -u root -l | grep -v '@reboot sleep 10s &&  echo illinois > /proc/sys/net/ipv4/tcp_congestion_control && echo illinois > /proc/sys/net/ipv4/tcp_allowed_congestion_control && echo fq > /proc/sys/net/core/default_qdisc'  | crontab -u root -
 cat /proc/sys/net/ipv4/tcp_congestion_control
   echo illinois > /proc/sys/net/ipv4/tcp_congestion_control
   echo illinois > /proc/sys/net/ipv4/tcp_allowed_congestion_control
   echo fq > /proc/sys/net/core/default_qdisc
(crontab -l; echo "@reboot sleep 10s &&  echo illinois > /proc/sys/net/ipv4/tcp_congestion_control && echo illinois > /proc/sys/net/ipv4/tcp_allowed_congestion_control && echo fq > /proc/sys/net/core/default_qdisc") | crontab - > /dev/null 2>&1
   echo -ne "\n\033[1;33mCongestionamento Atual : \033[1;37m"
 cat /proc/sys/net/ipv4/tcp_congestion_control
sleep 2s
   echo -ne "\n\033[1;32mCongestionamento Illinois Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
   ;;
   09 | 9)
echo -e "\033[1;33m Mtu Atual \033[1;37m"
echo ""
ifconfig eth0
echo -e "\033[0;31m------------------------------------\033[1;37m"
crontab -u root -l | grep -v '@reboot sleep 10s && ip link set dev eth0 mtu 9000'  | crontab -u root -
ip link set dev eth0 mtu 9000
(crontab -l; echo "@reboot sleep 10s && ip link set dev eth0 mtu 9000") | crontab - > /dev/null 2>&1
ifconfig eth0
echo -e "\033[0;31m------------------------------------\033[1;37m"
   echo -ne "\n\033[1;32mMtu Jumbo Frames Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
 ;;
10)
cd /bin/ && rm -f cwnd*
cd /bin/ && wget https://raw.githubusercontent.com/Rick3214/Rick3214-SERVER-MANAGER/main/SCRIPT%20Rick3214%20SERVER/SCRIPT%20Rick3214%20SERVER/FERRAMENTAS/cwnd > /dev/null 2>&1
cd /bin/ && chmod +x cwnd
echo -e "\033[1;33m Cwnd Atual \033[1;37m"
echo ""
ip route
echo -e "\033[0;31m------------------------------------\033[1;37m"
crontab -u root -l | grep -v '@reboot sleep 10s && cd /bin/ && cwnd'  | crontab -u root -
/sbin/ip route | while read p; do ip route change $p initcwnd 10 initrwnd 10 cwnd 10 mtu lock 9000 congctl lock illinois quickack 1; done
echo ""
ip route
echo -e "\033[0;31m------------------------------------\033[1;37m"
   echo -ne "\n\033[1;32mInitCwnd Tcp Definido !"
(crontab -l; echo "@reboot sleep 10s && cd /bin/ && cwnd") | crontab - > /dev/null 2>&1
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
   ;;
11)
cd /bin/ && rm -f vm*
cd /bin/ && wget https://raw.githubusercontent.com/Rick3214/Rick3214-SERVER-MANAGER/main/SCRIPT%20Rick3214%20SERVER/SCRIPT%20Rick3214%20SERVER/FERRAMENTAS/vm > /dev/null 2>&1
cd /bin/ && chmod +x vm
crontab -u root -l | grep -v '@reboot sleep 10s && cd /bin/ && vm'  | crontab -u root -
echo 1048576 > /proc/sys/fs/nr_open
echo 1048576 > /proc/sys/fs/file-max
echo 200 > /proc/sys/vm/vfs_cache_pressure
echo 100 > /proc/sys/vm/swappiness
echo 16 > /proc/sys/vm/page-cluster
echo 1 > /proc/sys/vm/dirty_background_ratio
echo 33554432 > /proc/sys/vm/overcommit_ratio
(crontab -l; echo "@reboot sleep 10s && cd /bin/ && vm") | crontab - > /dev/null 2>&1
   echo -ne "\n\033[1;32mAumento De Valores VM Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
   ;;
12)
echo -e "\033[1;33m Buffer/Cache Atual \033[1;37m"
echo ""
free -h
echo -e "\033[0;31m------------------------------------\033[1;37m"
echo ""
crontab -u root -l | grep -v '@daily echo 3 > /proc/sys/vm/drop_caches && echo 100 > /proc/sys/vm/swappiness'  | crontab -u root -
echo 3 > /proc/sys/vm/drop_caches
echo 100 > /proc/sys/vm/swappiness
(crontab -l; echo "@daily echo 3 > /proc/sys/vm/drop_caches && echo 100 > /proc/sys/vm/swappiness") | crontab - > /dev/null 2>&1
free -h
echo -e "\033[0;31m------------------------------------"
echo ""
   echo -ne "\n\033[1;32mBuffer/Cache Limpo! Definido Para Auto Limpeza 00:00Am"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
   ;;
13)
   echo -ne "\n\033[1;33mMelhor Funcionamento, Em Servidores Acima De 2 Nucleos."
crontab -u root -l | grep -v '@reboot sleep 10s && cd /bin/ && rps_cpu'  | crontab -u root -
cd /bin/ && rm -f rps_cpu*
cd /bin/ && wget https://raw.githubusercontent.com/Rick3214/Rick3214-SERVER-MANAGER/main/SCRIPT%20Rick3214%20SERVER/SCRIPT%20Rick3214%20SERVER/FERRAMENTAS/rps_cpu > /dev/null 2>&1
cd /bin && chmod +x rps_cpu
cd /bin/ && rps_cpu > /dev/null 2>&1
(crontab -l; echo "@reboot sleep 10s && cd /bin/ && rps_cpu") | crontab - > /dev/null 2>&1
sleep 2s
echo ""
   echo -ne "\n\033[1;32mRPS CPU Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
   ;;
   14 | 14)
crontab -u root -l | grep -v '@reboot sleep 10s && echo 4400000 > /scaling_max_freq && echo 1 > /sys/module/processor/parameters/ignore_ppc'  | crontab -u root -
echo 4400000 > /scaling_max_freq
echo 1 > /sys/module/processor/parameters/ignore_ppc
(crontab -l; echo "@reboot sleep 10s && echo 4400000 > /scaling_max_freq && echo 1 > /sys/module/processor/parameters/ignore_ppc") | crontab - > /dev/null 2>&1
   echo -ne "\n\033[1;32mFrequência Cpu Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
   ;;
15)
apt-get install haveged -y > /dev/null 2>&1
rm -f /etc/default/haveged
cd /etc/default && wget https://raw.githubusercontent.com/Rick3214/Rick3214-SERVER-MANAGER/main/SCRIPT%20Rick3214%20SERVER/SCRIPT%20Rick3214%20SERVER/FERRAMENTAS/haveged > /dev/null 2>&1
cd /etc/default && chmod +x haveged
service haveged restart > /dev/null 2>&1
service haveged start > /dev/null 2>&1
   echo -ne "\n\033[1;32mEntropia Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
;;
16)
echo -n > /etc/ssh/sshd_config
echo "X11Forwarding yes" >> /etc/ssh/sshd_config
echo "PrintMotd no" >> /etc/ssh/sshd_config
echo "AcceptEnv LANG LC_*" >> /etc/ssh/sshd_config
echo "Subsystem       sftp    /usr/lib/openssh/sftp-server" >> /etc/ssh/sshd_config
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
echo "Compression yes" >> /etc/ssh/sshd_config
echo "UseDNS yes" >> /etc/ssh/sshd_config
echo "UsePAM yes" >> /etc/ssh/sshd_config
echo "Authenticationmethods password" >> /etc/ssh/sshd_config
echo "Kexalgorithms diffie-hellman-group14-sha1" >> /etc/ssh/sshd_config
echo "Ciphers aes128-ctr" >> /etc/ssh/sshd_config
echo "MACs hmac-sha1" >> /etc/ssh/sshd_config
echo "Fingerprinthash MD5" >> /etc/ssh/sshd_config
echo "ClientAliveCountMax 15" >> /etc/ssh/sshd_config
echo "ClientAliveInterval 30s" >> /etc/ssh/sshd_config
echo "MaxStartups 20000" >> /etc/ssh/sshd_config
echo "MaxSessions 20000" >> /etc/ssh/sshd_config
echo "MaxAuthTries 20000" >> /etc/ssh/sshd_config
echo "LoginGraceTime 0s" >> /etc/ssh/sshd_config
echo "TCPKeepAlive yes" >> /etc/ssh/sshd_config
echo "ipqos af21 cs1" >> /etc/ssh/sshd_config
echo "Port 22" >> /etc/ssh/sshd_config
service sshd reload /dev/null 2>&1
echo -n > /etc/ssh/ssh_config
echo "Host *" >> /etc/ssh/ssh_config
echo "ControlMaster auto" >> /etc/ssh/ssh_config
echo "ControlPath ~/.ssh/%r@%h:%p" >> /etc/ssh/ssh_config
echo "ControlPersist 86400s" >> /etc/ssh/ssh_config
echo "ConnectTimeout 86400s" >> /etc/ssh/ssh_config
echo "Compression yes" >> /etc/ssh/ssh_config
echo "ConnectionAttempts 86400s" >> /etc/ssh/ssh_config
echo "Port 22" >> /etc/ssh/ssh_config
echo "ChallengeResponseAuthentication yes" >> /etc/ssh/ssh_config
echo "ClearAllForwardings yes" >> /etc/ssh/ssh_config
echo "ExitOnForwardFailure yes" >> /etc/ssh/ssh_config
echo "Pubkeyauthentication no" >> /etc/ssh/ssh_config
echo "PreferredAuthentications=password" >> /etc/ssh/ssh_config
echo "Kexalgorithms diffie-hellman-group14-sha1" >> /etc/ssh/ssh_config
echo "Ciphers aes128-ctr" >> /etc/ssh/ssh_config
echo "MACs hmac-sha1" >> /etc/ssh/ssh_config
echo "Fingerprinthash MD5" >> /etc/ssh/ssh_config
echo "ServerAliveCountMax 15" >> /etc/ssh/ssh_config
echo "ServerAliveInterval 30s" >> /etc/ssh/ssh_config
echo "TCPKeepAlive yes" >> /etc/ssh/ssh_config
echo "ipqos af21 cs1" >> /etc/ssh/ssh_config
service ssh reload /dev/null 2>&1
echo -n > /etc/host.conf
echo "order hosts,nospoof off,multi on,mdns on" >> /etc/host.conf
echo -ne "\n\033[1;32mMelhorias OpenSSH, Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
   ;;
17)
   echo -n > /etc/security/limits.conf
echo "root soft nproc unlimited" >> /etc/security/limits.conf
echo "root hard nproc unlimited" >> /etc/security/limits.conf
echo "root soft nofile 1048576" >> /etc/security/limits.conf
echo "root hard nofile 1048576" >> /etc/security/limits.conf
echo "root soft data unlimited" >> /etc/security/limits.conf
echo "root hard data unlimited" >> /etc/security/limits.conf
echo "root soft as unlimited" >> /etc/security/limits.conf
echo "root hard as unlimited" >> /etc/security/limits.conf
echo "root soft locks unlimited" >> /etc/security/limits.conf
echo "root hard locks unlimited" >> /etc/security/limits.conf
echo "root soft stack unlimited" >> /etc/security/limits.conf
echo "root hard stack unlimited" >> /etc/security/limits.conf
echo "root soft fsize unlimited" >> /etc/security/limits.conf
echo "root hard fsize unlimited" >> /etc/security/limits.conf
echo "root soft memlock unlimited" >> /etc/security/limits.conf
echo "root hard memlock unlimited" >> /etc/security/limits.conf
echo "root soft msgqueue unlimited" >> /etc/security/limits.conf
echo "root hard msgqueue unlimited" >> /etc/security/limits.conf
echo "root soft sigpending unlimited" >> /etc/security/limits.conf
echo "root hard sigpending unlimited" >> /etc/security/limits.conf
echo "root soft priority -11" >> /etc/security/limits.conf
echo "root hard priority -11" >> /etc/security/limits.conf
echo "root soft nice -11" >> /etc/security/limits.conf
echo "root hard nice -11" >> /etc/security/limits.conf
echo -ne "\n\033[1;32mAumento De Limites, Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
;;
18)
chattr -i /etc/resolv.conf
rm /etc/resolv.conf
echo "options rotate timeout:1 attempts:1 use-vc single-request-reopen edns0" >> /etc/resolv.conf
echo "search www.google.com" >> /etc/resolv.conf
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
echo "nameserver 8.8.4.4" >> /etc/resolv.conf
chmod +x /etc/resolv.conf
chattr +i /etc/resolv.conf
/etc/init.d/networking restart > /dev/null 2>&1
echo -e "\033[1;33m"
cat /etc/resolv.conf
echo ""
echo -ne "\n\033[1;32mDns Google, Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
;;
19)
chattr -i /etc/resolv.conf
rm /etc/resolv.conf
echo "options rotate timeout:1 attempts:1 use-vc single-request-reopen edns0" >> /etc/resolv.conf
echo "search www.google.com" >> /etc/resolv.conf
echo "nameserver 208.67.222.222" >> /etc/resolv.conf
echo "nameserver 208.67.220.220" >> /etc/resolv.conf
chmod +x /etc/resolv.conf
chattr +i /etc/resolv.conf
/etc/init.d/networking restart > /dev/null 2>&1
echo -e "\033[1;33m"
cat /etc/resolv.conf
echo ""
echo -ne "\n\033[1;32mDns OpenDns, Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
;;
20)
chattr -i /etc/resolv.conf
rm /etc/resolv.conf
echo "options rotate timeout:1 attempts:1 use-vc single-request-reopen edns0" >> /etc/resolv.conf
echo "search www.google.com" >> /etc/resolv.conf
echo "nameserver 1.1.1.1" >> /etc/resolv.conf
echo "nameserver 1.0.0.1" >> /etc/resolv.conf
chmod +x /etc/resolv.conf
chattr +i /etc/resolv.conf
/etc/init.d/networking restart > /dev/null 2>&1
echo -e "\033[1;33m"
cat /etc/resolv.conf
echo ""
echo -ne "\n\033[1;32mDns CloudFlare, Definido !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
cd /bin/ && mtuning
;;
21)
crontab -u root -l | grep -v '@reboot sleep 10s && mount -o remount,noatime,nodiratime,nobarrier auto / && mount -o remount,noatime,nodiratime, auto /dev && mount -o remount,noatime,nodiratime, auto /proc && mount -o remount,noatime,nodiratime, auto /sys && mount -o remount,noatime,nodiratime,nobarrier auto /mnt'  | crontab -u root -
mount -o remount,noatime,nodiratime,nobarrier auto / > /dev/null 2>&1
mount -o remount,noatime,nodiratime, auto /dev > /dev/null 2>&1
mount -o remount,noatime,nodiratime, auto /proc > /dev/null 2>&1
mount -o remount,noatime,nodiratime, auto /sys > /dev/null 2>&1
mount -o remount,noatime,nodiratime,nobarrier auto /mnt > /dev/null 2>&1
(crontab -l; echo "@reboot sleep 10s && mount -o remount,noatime,nodiratime,nobarrier auto / && mount -o remount,noatime,nodiratime, auto /dev && mount -o remount,noatime,nodiratime, auto /proc && mount -o remount,noatime,nodiratime, auto /sys && mount -o remount,noatime,nodiratime,nobarrier auto /mnt") | crontab - > /dev/null 2>&1
echo ""
clear
findmnt
echo ""
echo -ne "\n\033[1;32mRemontado Com Sucesso !"
echo ""
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
   ;;
off | OFF)
echo -n > /etc/sysctl.conf
crontab -u root -l | grep -v '@reboot sleep 10s &&  echo bbr > /proc/sys/net/ipv4/tcp_congestion_control && echo bbr > /proc/sys/net/ipv4/tcp_allowed_congestion_control && echo fq > /proc/sys/net/core/default_qdisc'  | crontab -u root -
crontab -u root -l | grep -v '@reboot sleep 10s &&  echo illinois > /proc/sys/net/ipv4/tcp_congestion_control && echo illinois > /proc/sys/net/ipv4/tcp_allowed_congestion_control && echo fq > /proc/sys/net/core/default_qdisc'  | crontab -u root -
crontab -u root -l | grep -v '@daily echo 3 > /proc/sys/vm/drop_caches'  | crontab -u root -
crontab -u root -l | grep -v '@reboot sleep 10s && echo 4400000 > /scaling_max_freq && echo 1 > /sys/module/processor/parameters/ignore_ppc'  | crontab -u root -
crontab -u root -l | grep -v '@reboot sleep 10s && cd /bin/ && rps_cpu'  | crontab -u root -
crontab -u root -l | grep -v '@reboot sleep 10s && /bin/acksyshttpack'  | crontab -u root -
crontab -u root -l | grep -v '@reboot sleep 10s && mount -o remount,noatime,nodiratime,nobarrier auto / && mount -o remount,noatime,nodiratime, auto /dev && mount -o remount,noatime,nodiratime, auto /proc && mount -o remount,noatime,nodiratime, auto /sys && mount -o remount,noatime,nodiratime,nobarrier auto /mnt'  | crontab -u root -
crontab -u root -l | grep -v '@reboot sleep 10s && cd /bin/ && cwnd'  | crontab -u root -
crontab -u root -l | grep -v '@reboot sleep 10s && cd /bin/ && vm'  | crontab -u root -
crontab -u root -l | grep -v '@reboot sleep 10s && ip link set dev eth0 mtu 9000'  | crontab -u root -
apt-get remove haveged -y > /dev/null 2>&1
echo -n > /etc/security/limits.conf
echo -n > /etc/rc.local
chattr -i /etc/resolv.conf
/etc/init.d/networking restart > /dev/null 2>&1
cd /bin/ && rm -f rps_cpu*
cd /bin/ && rm -f cwnd*
cd /bin/ && rm -f vm*
echo -ne "\n\033[1;32mQualquer Ajuste Aplicado, Foi Removido! Reinicie Seu Servidor ."
echo ""
echo ""
echo -ne "\033[1;37mAperte Enter"; read
   ;;
menu | MENU)
clear
menu
;;
   *)
esac
done
clear
}
cd /bin/ && mtuning
#fim

